In [1]:
import csv
import pandas as pd
from functions import *

data = []

with open('DATA/Police.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        data.append(row)

print(data[0])

df = pd.DataFrame(data[1:], columns=data[0])

['custody_id', 'participant_age_group', 'participant_gender', 'participant_status', 'participant_type', 'latitude', 'longitude', 'gun_stolen', 'gun_type', 'incident_id', 'date_fk']

In [2]:
old_tab, new_tab = add_unique_ids_2(data, ['latitude', 'longitude'], "geo_id")

In [3]:
import pandas as pd

old_tab = pd.DataFrame(old_tab[1:], columns=old_tab[0])
new_tab = pd.DataFrame(new_tab[1:], columns=new_tab[0])

# join the two tables on the id column
new_tab = new_tab.set_index('geo_id')
old_tab = old_tab.set_index('geo_id')

joined = old_tab.join(new_tab, on=['geo_id'], how='left')

joined

,custody_id,participant_age_group,participant_gender,participant_status,participant_type,gun_stolen,gun_type,incident_id,date_fk,latitude,longitude
geo_id,,,,,,,,,,,
0,10,Adult 18+,Male,Arrested,Suspect,Stolen,Shotgun,2,0,41.4455,-82.1377
1,336,Adult 18+,Male,Arrested,Suspect,Stolen,Shotgun,56,20,29.8736,-90.0568
2,1194,Adult 18+,Male,Arrested,Suspect,Stolen,Shotgun,209,70,39.9272,-82.0073
3,1244,Adult 18+,Male,Arrested,Suspect,Stolen,Shotgun,219,73,36.1189,-95.8429
4,1605,Adult 18+,Male,Arrested,Suspect,Stolen,Shotgun,312,86,30.6884,-87.048
...,...,...,...,...,...,...,...,...,...,...,...
15243,306358,Adult 18+,Male,Unharmed,Suspect,Unknown,300 Win,171908,1223,29.6852,-95.375
16075,318662,Adult 18+,Male,Arrested,Suspect,Unknown,300 Win,179476,1269,31.1783,-84.5261
95653,369347,Adult 18+,Male,Arrested,Suspect,Unknown,300 Win,210439,1446,33.2804,-86.8003
55124,107231,Teen 12-17,Male,Arrested,Suspect,Not-stolen,16 gauge,55629,478,29.9642,-90.1288
95654,202387,Adult 18+,Male,Killed,Suspect,Not-stolen,300 Win,110940,850,36.0064,-80.8405

In [4]:
df

,custody_id,participant_age_group,participant_gender,participant_status,participant_type,latitude,longitude,gun_stolen,gun_type,incident_id,date_fk
0,10,Adult 18+,Male,Arrested,Suspect,41.4455,-82.1377,Stolen,Shotgun,2,0
1,336,Adult 18+,Male,Arrested,Suspect,29.8736,-90.0568,Stolen,Shotgun,56,20
2,1194,Adult 18+,Male,Arrested,Suspect,39.9272,-82.0073,Stolen,Shotgun,209,70
3,1244,Adult 18+,Male,Arrested,Suspect,36.1189,-95.8429,Stolen,Shotgun,219,73
4,1605,Adult 18+,Male,Arrested,Suspect,30.6884,-87.048,Stolen,Shotgun,312,86
...,...,...,...,...,...,...,...,...,...,...,...
170923,306358,Adult 18+,Male,Unharmed,Suspect,29.6852,-95.375,Unknown,300 Win,171908,1223
170924,318662,Adult 18+,Male,Arrested,Suspect,31.1783,-84.5261,Unknown,300 Win,179476,1269
170925,369347,Adult 18+,Male,Arrested,Suspect,33.2804,-86.8003,Unknown,300 Win,210439,1446
170926,107231,Teen 12-17,Male,Arrested,Suspect,29.9642,-90.1288,Not-stolen,16 gauge,55629,478
170927,202387,Adult 18+,Male,Killed,Suspect,36.0064,-80.8405,Not-stolen,300 Win,110940,850